name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: medieval-cue-splitter-portable-${{ github.ref_name }}.zip
      version: 7.0.10
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://github.com/KiCad/kicad-source-mirror/releases/download/${{ env.version }}/kicad-${{ env.version }}-x86_64.exe -L --output installer.exe
          
      - shell: cmd
        run: |
          set __COMPAT_LAYER=RUNASINVOKER &&^
          .\installer.exe /currentuser /S /D="1234" &&^
          dir
          
      # - shell: cmd
      #   run: xcopy /H /Y /C "CUE_Splitter.exe.Portable.cmd" "E8B158F"
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "E8B158F"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "E8B158F/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
