name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: kicad-portable-${{ github.ref_name }}.zip
      version: 8.0.4
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: | 
          curl https://github.com/KiCad/kicad-source-mirror/releases/download/${{ env.version }}/kicad-${{ env.version }}-x86_64.exe -L --output installer.exe
          
      - shell: cmd
        run: |
          set __COMPAT_LAYER=RUNASINVOKER &&^
          .\installer.exe /currentuser /S &&^
          dir
          
      - shell: cmd
        run: |
          xcopy /H /Y /C "kicad.exe.Portable.cmd" "%LOCALAPPDATA%\Programs\KiCad\8.0\bin\"
        
      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Programs\KiCad\8.0" &&^
          7z.exe a "${{ github.workspace }}\${{ env.targetZip }}" &&^
          dir
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
